### ISSUE TITLE
[Core]: Write or rewrite ReactionRegistry docs

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#12]
Make ReactionRegistry easier to understand

**Comment by aaronjudd** [comment]
To be clear, this issue would be to rewrite: https://docs.reactioncommerce.com/reaction-docs/development/registry

**Comment by machikoyasuda** [comment]
https://blog.reactioncommerce.com/an-intro-to-architecture-the-registry/
