### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by anhldbk** [reactioncommerce/reaction-docs#167]
Sometimes the loading screen took forever. Here's what it looks like:

![screenshot from 2017-03-15 06-33-53](https://cloud.githubusercontent.com/assets/3270746/23926931/96d31f86-0949-11e7-87b6-e6632ce30d0b.png)

**Comment by aaronjudd** [comment]
That might have been from switching to the 0.19 branch.  We don't have an elegant way of saying, "hey, this doc doesn't exist in this branch".  A refresh usually helps if this isn't the case.

**Comment by anhldbk** [comment]
@aaronjudd Even if I refresh the page, the bug still occurs

**Comment by aaronjudd** [comment]
did you try choosing another branch?

**Comment by michael-alade** [comment]
@aaronjudd This seems to be working fine already.

**Comment by michael-alade** [comment]
Just tested it again. It's still happening.

**Comment by zenweasel** [comment]
I think this is the issue with internal links. Links from the navigation seem to work.

**Comment by machikoyasuda** [comment]
@michael-alade Just pushed URL fixes so this bug should be fixed now. Mind re-testing and closing this issue if you don't get the bug anymore?
