### ISSUE TITLE
Setup multiple store 

### ISSUE THREAD

**Issue by rohan5894** [reactioncommerce/reaction-docs#193]
HI,
Can you please let setup multiple store functionality exist this Meteor app .i need any seller to be able to sell their item. 

If this functionality are  exist then how can i setup this

**Comment by machikoyasuda** [comment]
Hi @rohan5894 - Marketplace functionality has been live as of 1.5. You can see the docs here for how to set this up: https://docs.reactioncommerce.com/reaction-docs/master/merchant-shop-setup
