### ISSUE TITLE
Example of modifying product and adding new fields

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-docs#226]
We need an example that walks through building a plugin that modifies the product schema and alters the PDP layout, adding new fields.  Would also be useful if the example carried through the cart/checkout customization at some point as well.

https://github.com/reactioncommerce/reaction-example-plugin

**Comment by zenweasel** [comment]
Hopefully, soon we will have a lot of learning about writing plugins and I think we need to revisit this whole thing.

**Comment by machikoyasuda** [comment]
@prinzdezibel has done this with https://docs.reactioncommerce.com/reaction-docs/master/extending-product-schema-location-map

Marking as closed.
