### ISSUE TITLE
Add community plugins/packages/themes/recommendations list

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#234]
Create a page with:
- Recommended Meteor plugins
- Reaction plugins by the community
- Reaction themes by the community

**Comment by machikoyasuda** [comment]
Add https://github.com/curranabell/customReactionTheme

**Comment by machikoyasuda** [comment]
Add https://github.com/kahmali/meteor-restivus from https://gitter.im/reactioncommerce/reaction?at=5977366f329651f46ebf0157

**Comment by aaronjudd** [comment]
We might want to have them grouped by version compatibility, tested, something like that?  There are lots of plugins out there that could be used as code examples, ie: bitcoin, indian payments, COD, the getOutfitted shipstation, rental packages, etc.. but all of these are older and would need likely need significant updates (but still useful for reference).

**Comment by acreilly** [comment]
I am posting some that I have found:
https://github.com/hydrotik/reaction-hydrotik-plugin
https://github.com/curranabell/customReactionTheme

**Comment by acreilly** [comment]
https://github.com/danielsouzapinna/regionalization

**Comment by machikoyasuda** [comment]
thanks @iamchathu for starting this awesome list! https://github.com/iamchathu/awesome-reactioncommerce

**Comment by iamchathu** [comment]
@machikoyasuda thanks for the mention. I would like to get community help on filling this list

**Comment by machikoyasuda** [comment]
https://github.com/joshuacox/reaction-generic-theme

**Comment by machikoyasuda** [comment]
In development: by @boomerdigital - Recurring subscription billing stripe integration https://github.com/boomerdigital/reaction-subscription-billing/

**Comment by zenweasel** [comment]
A couple more:
https://github.com/carlos-olivera/reactioncommerce-json-importer
https://github.com/loanlaux/reaction-hydrotik-plugin (an undated fork of the Hydrotix plugin)

**Comment by prinzdezibel** [comment]
Rolled out. Done.
