### ISSUE TITLE
New subnav design

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#243]

**Comment by zrisher** [comment]
It would be nice if the new design scrolled to show your active page, and had some indicator of the active page if you're on one of the section introductions.

Right now, if I navigate to https://docs.reactioncommerce.com/ and click "Developer Guide", it directs me to the same page as if I were to click "Developer" in the side nav. However, the side nav doesn't scroll down to reveal this section, and the page I'm viewing isn't shown to be "active" (unlike the subsection pages, which highlight red when I navigate to them). So after reading the first page of the developer guide I'm left with the question of "where's the next page?" I have to scroll down the list, find the (unstyled) page that I'm currently on, and then click the buttons below it.

**Comment by machikoyasuda** [comment]
Moving to `redoc`
