### ISSUE TITLE
[Guides]: Add performance tuning section

### ISSUE THREAD

**Issue by joshuacox** [reactioncommerce/reaction-docs#249]
While developing on my laptop I thought ReactionCommerce was a little slow (sometimes nearly 10 seconds to load the front page).  I didn't think much of it, as I'm used to things running slow on my Acer C720 chromebook that I put full linux on, it often struggles.

But now I've moved my setup to a server with 32 cpu cores, 128GB of RAM, hardware RAID-6 on six drives, a cluster of mongos, and I'm still seeing 10 seconds page loads at worst, over a second at best.  Is there some 'caching' I'm forgretting to implement?

**Comment by machikoyasuda** [comment]
Closing
