### ISSUE TITLE
Broken link on Layouts

### ISSUE THREAD

**Issue by selloutdesign** [reactioncommerce/reaction-docs#276]
The link for changing the index page layout:
https://docs.reactioncommerce.com/reaction-docs/development/layout
goes to an endless spinner

**Comment by machikoyasuda** [comment]
Hi @selloutdesign - that is a dead link now that we've deprecated the `development` branch. Sorry about that. Here's the current URL: https://docs.reactioncommerce.com/reaction-docs/master/layout
