### ISSUE TITLE
[Core]: How should we write event hook documentation?

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-docs#278]
This post is to start a discussion about how best to document event hooks in Reaction.

We have event hooks, method hooks, and collection hooks in Reaction. 
I'd like to focus this issue on event hooks, if you feel that we need to talk about method hooks or collection hooks, please start another issue.

I'll start off by saying that - at the core - event hooks are fairly well defined. You can read through that documentation here: https://github.com/reactioncommerce/reaction/blob/marketplace/server/api/hooks.js#L41-L58

I'd like to talk about how to document specific, named hooks, such as the [afterCoreInit hook](https://github.com/reactioncommerce/reaction/blob/marketplace/server/api/core/core.js#L53) or the [onGetShippingRates hook](https://github.com/reactioncommerce/reaction/blob/marketplace/server/methods/core/shipping.js#L117)

I'd also like to talk about naming conventions for hooks. What types of names should we use? Should they all be action sounding names (on, after, before, etc) and what criteria should we use to decide that?

I think theres some merit to documenting hooks in the same way that we document methods, but using a different `@module`. Not sure how this will play out in the docs though @machikoyasuda 

So here's an example hook doc that I wrote that you guys should proceed to tear apart.
```
/**
 * Hook for affecting the application fee charged. Any hooks that `add` "onCalculateStripeApplicationFee" will
 * run here
 * @module hooks/payments/stripe
 * @method onCalculateStripeApplicationFee
 * @param {number} applicationFee the exact application fee in cents (mutable by the hook)
 * @param {object} options object containing non mutable properties passed into the hook
 * @param {object} options.cart the cart object - non-mutable
 * @param {object} options.shopId the shopId - non-mutable
 * @todo Consider abstracting the application fee out of the Stripe implementation
 * @returns undefined - but mutates the applicationFee
 */
Hooks.Events.run("onCalculateStripeApplicationFee", applicationFee, {
  cart, // The cart
  shopId // currentShopId
});
```

**Comment by machikoyasuda** [comment]
- Method Hooks are deprecated since https://github.com/reactioncommerce/reaction/pull/4915
- Collection Hooks are deprecated since v1.10.0 https://github.com/reactioncommerce/reaction/pull/4035 https://github.com/reactioncommerce/reaction/pull/4036 https://github.com/reactioncommerce/reaction/pull/3889
- Event Hooks have been replaced with appEvents since https://github.com/reactioncommerce/reaction/pull/4915

This issue should be closed and replaced with an issue to deprecate Hooks docs.
