### ISSUE TITLE
Add details explaining changes to from roles to Groups

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction-docs#299]
Things around the fact that:

The previous `shop.defaultVisitorRoles` are the roles now defined in the `guest` group.
Also, the previous `shop.defaultCustomerRoles` are the roles now defined in the default `customer` group.

So a previous reference to `shop.defaultVisitorRoles` should now use the group object (e.g `Groups.find({slug: "guest"}).permissions`).

The default list of those roles that we had on the Shop schema are present on server export of Reaction (i.e Reaction.default...)

Ref: https://github.com/reactioncommerce/reaction/issues/2183

**Comment by machikoyasuda** [comment]
Closed w/ https://github.com/reactioncommerce/reaction-docs/pull/311

**Comment by impactmass** [comment]
Hi @machikoyasuda .. #311 did not actually cover everything for this ticket. I could have combined then but didn't think about it. I can get this in soon too (should not be more than a few sentences).
