### ISSUE TITLE
Some Broken Links

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#30]
I will fix what I can, but just putting these in here for reference.

On home page, link to OngoWorks doesn't work

* On https://docs.reactioncommerce.com/reaction-docs/development/using-velocity-for-testing
Link to Velocity is broken

On https://docs.reactioncommerce.com/reaction-docs/master/i18n
Link to `themes.md` is broken

On https://docs.reactioncommerce.com/reaction-docs/master/templates
Link to `styleguide.md` is broken

On https://docs.reactioncommerce.com/reaction-docs/development/reaction-import
Link to Tom's `reaction-import` repo is broken

On https://docs.reactioncommerce.com/reaction-docs/development/deploying
Links to Galaxy, Docker and AWS are broken.

**Comment by joseconstela** [comment]
AWS removed?

**Comment by joseconstela** [comment]
Never mind, just saw it was referenced in the Docker one
