### ISSUE TITLE
[Developer] Create SUPPORT.md

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#329]
Detail Support expectations

**Comment by zenweasel** [comment]
Did we actually do this or just close the ticket?

**Comment by machikoyasuda** [comment]
Closing this ticket in favor of https://github.com/reactioncommerce/reaction-docs/issues/451

**Comment by zenweasel** [comment]
This document should delineate what types of support should be expected through what channels, what sort of things we expect from Issues, etc. Also the revised PR process that we are talking about. One of the main purposes should be to curb abuse of these channels and to set expectations.

**Comment by machikoyasuda** [comment]
combining with #451
