### ISSUE TITLE
[Tutorial]: Remove all references to Blaze from Customization guide

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#335]
We don't want to be recommending people use something that we are rapidly eliminating and I think we need to carefully comb through all the docs and make sure don't have any outdated references.

**Comment by machikoyasuda** [comment]
Semi duplicate https://github.com/reactioncommerce/reaction-docs/issues/265

**Comment by machikoyasuda** [comment]
done
