### ISSUE TITLE
Developer FAQ - What sites are using Reaction?

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#338]
"What sites are using Reaction"

**Comment by prinzdezibel** [comment]
What about just referring to our forum?
https://forums.reactioncommerce.com/t/share-your-reaction-shop/331/20

**Comment by zenweasel** [comment]
No. I think we should soon be able to point at our community showcase page but for now I would like to have a curated list. That thread is full of a lot of not-related-to-this-question stuff.

**Comment by machikoyasuda** [comment]
I got this one @prinzdezibel :)
