### ISSUE TITLE
Developer FAQ - I want to use XYZ payment provider/Shipper how do I do that?

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#341]

**Comment by prinzdezibel** [comment]
This FAQ could be an opportunity to migrate the old COD package to a plugin and create a tutorial to explain how to do it actually.

https://github.com/Gouthamve/reaction-cod

**Comment by prinzdezibel** [comment]
Now I've realized that there's already a "how-to-create-a-payment-provider" tutorial. Not sure if it makes sense to merge that with a new cod-payment-plugin-tutorial somehow.

For now, I've just added a new FAQ to our documentation which links to the existing tutorial:
https://github.com/reactioncommerce/reaction-docs/pull/380/files

**Comment by zenweasel** [comment]
Closed via #380
