### ISSUE TITLE
[Developer FAQ] How do I add HTML/markup to my product descriptions?

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#355]

**Comment by prinzdezibel** [comment]
Hint: For the link to work, this PR must be approved and merged into master:

https://github.com/reactioncommerce/reaction-docs/pull/358

**Comment by prinzdezibel** [comment]
Done. going to close.
https://docs.reactioncommerce.com/reaction-docs/master/faqs
