### ISSUE TITLE
[Developer FAQ] What do I need to know to work with Reaction?

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#357]
What languages, frameworks should I be familiar with? What skills do I need to have?

**Comment by machikoyasuda** [comment]
Answered here: https://docs.reactioncommerce.com/reaction-docs/master/plugin-intro-1#what-do-i-need-to-know-to-create-a-plugin

**Comment by zenweasel** [comment]
Yeah, I think it should probably get copied or moved from there into the FAQ. I think people want to know that before they commit to sitting down and reading the Tutorial.

**Comment by prinzdezibel** [comment]
@zenweasel @machikoyasuda albeit it seems a bit verbose for a FAQ format. I'll try to condense the spirit of it and put it in developer's FAQ section, ok?

**Comment by zenweasel** [comment]
Should also probably remove Blaze and add React to that if you haven't already

**Comment by prinzdezibel** [comment]
Done.
