### ISSUE TITLE
[Developer FAQ] How do I change the favicon?

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#359]
Seriously, I don't know.

**Comment by jshimko** [comment]
The favicon for each platform is all sourced from here (also see entire file):

https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/default-theme/client/favicons.js#L1-L8

You could generate your own favicon image set and host them wherever, then change that `basePath` variable to point to it.  Obviously, this isn't very configurable right now, but you can look at that code and see how that could fairly easily change.

**Comment by prinzdezibel** [comment]
Fixed via #369 and #398.
