### ISSUE TITLE
[Components]: Add docs for Form component

### ISSUE THREAD

**Issue by efalayi** [reactioncommerce/reaction-docs#378]
- What are the props in the Form component used for?
- What props are compulsory?
- What props can be overridden?
- What is the type of value expected in each prop?
- Can the schema prop have a branched data?
- How can the form component  accommodate branched schema data?
- How can it be done to place form elements side by side?

**Comment by prinzdezibel** [comment]
Could be that our own Component.Form will be superseded by http://forms.dairystatedesigns.com/reacto-form/ at some day in future. Not sure about the scope of both initiatives, though..

**Comment by machikoyasuda** [comment]
Issue moved to [reactioncommerce/reaction-component-library #7](https://github.com/reactioncommerce/reaction-component-library/issues/7) via [**ZenHub**](https://www.zenhub.com/)
