### ISSUE TITLE
Consider to remove page "Templates"

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction-docs#403]
I'd propose to eliminate the page

https://docs.reactioncommerce.com/reaction-docs/master/templates

altogether, because its content deals completely with deprecated Blaze technology.

**Comment by machikoyasuda** [comment]
Should we have an official way of "deprecating" pages instead of removing them entirely?

Maybe we can:
1. Remove it from the sidebar
2. Don't delete the markdown file entirely, so URLs dont break
3. Add deprecation warning message to the top

@zenweasel

**Comment by zenweasel** [comment]
@machikoyasuda yes, good call. And maybe a note at the top that explains why it's deprecated.

If we do that, I am all for removing this page as it's no longer relevant

**Comment by prinzdezibel** [comment]
Fixed via https://github.com/reactioncommerce/reaction-docs/pull/407
