### ISSUE TITLE
Star us on Github button cut off. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-docs#413]
The star us on Github button is being cut off.

<img width="1436" alt="reaction_docs_-_introduction" src="https://user-images.githubusercontent.com/20409254/33782476-be7869f0-dc0d-11e7-8ac4-21a6902d1d90.png">

**Comment by machikoyasuda** [comment]
Closing in favor of https://github.com/reactioncommerce/redoc/issues/83
