### ISSUE TITLE
UI Component Images/Screenshots

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction-docs#419]
Hello, when y'all have some time, I would love to see renderings of each of the [UI Components](https://docs.reactioncommerce.com/reaction-docs/master/components).
Ideally, an index page would show them all.
My issue is that I usually have an idea of how something should look, I just don't know which Component I should be using.

thanks!

**Comment by mikemurray** [comment]
Wouldn't hurt to include screenshots in the static docs. For now we have some of those components as live demos or at https://styleguide.reactioncommerce.com/

**Comment by mikemurray** [comment]
We should probably also link each component doc to their corresponding component in the styleguide.

**Comment by machikoyasuda** [comment]
Closing this issue b/c we are now going to be deprecating the old style guide and doing this in https://github.com/reactioncommerce/reaction-component-library
