### ISSUE TITLE
Create documentation for Migrations

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#422]
It wasn't going to be a supported API but it appears it is now

**Comment by prinzdezibel** [comment]
How can I see the difference between a "supported" and "unsupported" API?

**Comment by zenweasel** [comment]
There is no difference. I just meant that the migrations package was just going to be a temporary solution but it's turned into a permanent solution so we should document it. Sorry for the confusing note.

**Comment by prinzdezibel** [comment]
@zenweasel: Thinking about how a migration strategy could look like, not only from a Reaction-internal standpoint,  but also from a user's perspective. Somehow we need to think about how to provide our users a migration path for the database modifications she/he needs to do. So I've been playing quite a bit today and will summarize my thoughts hereafter ..

But first: dinner time :)

**Comment by zenweasel** [comment]
I would prefer we just document the existing migration scheme for now
