### ISSUE TITLE
[Developer]: Create "Communication" or "How to contact Us" page with all relevant channels/emails

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#451]
Should be in FAQ's, etc/

**Comment by machikoyasuda** [comment]
Dev FAQ - https://docs.reactioncommerce.com/reaction-docs/master/developer-faq
Operator FAQ - https://docs.reactioncommerce.com/reaction-docs/master/faqs

The last question on both of the FAQs have contact info to Forums, Gitter, community call. What else should we add?

**Comment by machikoyasuda** [comment]
https://github.com/reactioncommerce/reaction-docs/issues/329

**Comment by machikoyasuda** [comment]
Issue moved to [reactioncommerce/reaction-docs-static #38](https://github.com/reactioncommerce/reaction-docs-static/issues/38) via [**ZenHub**](https://www.zenhub.com/)
