### ISSUE TITLE
Guide: Add instructions for running the Docker image for people who just want to evaluate

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#458]
For non-developers who just run to run Reaction locally to try it out, just running the docker container might be a more "frictionless" experience so we should make this more apparent in the installation docs.

This is probably especially true for Windows which still has the most difficult install experience.

**Comment by vwadher** [comment]
Cindy and I were just talking about this! Pushing docker as the "preferred" windows install method would be good.

**Comment by zenweasel** [comment]
As discussed, we also might want to consider suggesting Kitematic for people who are adverse to the command line (which is probably **very** common for non-developer Windows users)

**Comment by aaronjudd** [comment]
That would require explaining how to install Docker (which in itself, is not always easy).  This is the approach we'll be taking in reaction:next most likely (installing our own versions, via the CLI).

It cannot be the "preferred" method for development right now, only for evaluation..

**Comment by zenweasel** [comment]
Should we have separate "developer" and "evaluator" instructions maybe? Maybe a "Just want to try out Reaction?" and a "Looking to develop on Reaction?" pathway.

**Comment by mattt416** [comment]
Take a look at https://church.io/onebody/, specifically the `Install in the Cloud` link.  I've not tested this personally but assuming this works it seems like a really frictionless way of getting someone a playground setup with minimal fuss and minimal spend.  Like @aaronjudd said, helping get someone setup w/ Docker/VirtualBox/whatever is a greater challenge than helping them get Reaction Commerce installed and running.

**Comment by aldeed** [comment]
Seems like this is resolved at this point
