### ISSUE TITLE
Broken link in FAQ section

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#46]
The link for `spiderable` on Meteorpedia is broken because it is `https://` but Meteorpedia doesn't support it

**Comment by zenweasel** [comment]
Link to relevant version in Meteor Guide instead

**Comment by aaronjudd** [comment]
Let's update to the Meteor guide.. and remove the meteor pedia - it's getting out of date.

**Comment by zenweasel** [comment]
I took long enough to deal with this that there no longer is anything in the Meteor guide about Spiderable. So just going to remove the link
