### ISSUE TITLE
Release 1.8 - Rename Media to BrandAssets

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#490]
Update https://docs.reactioncommerce.com/reaction-docs/master/image-handling to reflect changes upcoming in Release 1.8 https://github.com/reactioncommerce/reaction/pull/3558

**Comment by prinzdezibel** [comment]
@machikoyasuda I don't think we need changes to that document. The collection is still called Media,
 because it still contains all images, not only the brand asset. The subscription name for retrieving the brand assets has changed though, but those subscription name is not referenced in the URL.

**Comment by prinzdezibel** [comment]
If you agree, please close. Or let me know if I got something wrong. thanks.

**Comment by machikoyasuda** [comment]
@prinzdezibel Got it! Closing.
