### ISSUE TITLE
Core: Deprecating collection hooks

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#501]
Update:
- https://docs.reactioncommerce.com/reaction-docs/master/collection-hooks
- https://docs.reactioncommerce.com/reaction-docs/master/reaction-inventory
- https://docs.reactioncommerce.com/reaction-docs/master/collections#reaction-collections

with the latest from:

https://github.com/reactioncommerce/reaction/pull/3642

**Comment by spencern** [comment]
@machikoyasuda is this still in progress?
