### ISSUE TITLE
[Core] add instructions for Stripe Connect from localhost

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#509]
as requested here https://github.com/reactioncommerce/reaction-docs/issues/441

Would it be possible to also include how to do this from localhost? And if it's not possible add that for clarity. Cheers

**Comment by prinzdezibel** [comment]
@machikoyasuda Where should that instruction go exactly?

**Comment by machikoyasuda** [comment]
@prinzdezibel https://github.com/reactioncommerce/reaction-docs/blob/master/admin/marketplace-merchant-setup.md
