### ISSUE TITLE
[Docs/Core] Audit, standardize and document all Error messaging in app

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#513]
- https://github.com/reactioncommerce/reaction/pull/3538/files#diff-9ef1c7def4fdab310138484898aa6368R100 from @aaronjudd 

Document what errors we have now for the actual error messaging.

**Comment by machikoyasuda** [comment]
@zenweasel Is this the relevant Issue from core? https://github.com/reactioncommerce/reaction/issues/3122

**Comment by zenweasel** [comment]
Yes

**Comment by zenweasel** [comment]
Looking through the code we have, the "standard" ones we could reuse, although I don't we can restrict it to these
```
access-denied
not-implemented
invalid-parameter
not-configured
server-error
not-found
```
