### ISSUE TITLE
Create acceptance test scripts for Avalara

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#514]
We need some acceptance tests that tell how to test Avalara with some specifics including checking in the Avalara administrative panel and what things we expect like:

1. Being able to exclude a particular item from being taxable
1. Being able to exclude a customer as non-taxable
1. Being able to set the taxcode for a product and have it reflected in the admin console
1. Shipping should show up as non-taxable when shipping from CA-to-CA

(I have an Avalara checklist somewhere, but ^^^ would be a good start)

**Comment by machikoyasuda** [comment]
Closing re: https://github.com/reactioncommerce/reaction/issues/4308
