### ISSUE TITLE
installation doc incorrect?

### ISSUE THREAD

**Issue by mswaidan** [reactioncommerce/reaction-docs#52]
Installation doc reads:
> To install and run Reaction locally:
>
```
> curl https://install.meteor.com | /bin/sh
> git clone https://github.com/reactioncommerce/reaction.git
> cd reaction
> reaction pull
> reaction
```
>

Isn't this more accurate? :

> To install and run Reaction locally:
> 
```
> curl https://install.meteor.com | /bin/sh
> git clone https://github.com/reactioncommerce/reaction.git
> cd reaction
> npm install -g reaction-cli</b>
> reaction pull
> reaction
```

**Comment by jshimko** [comment]
The CLI will ask if you want Meteor installed if you don't have it already and it does the `git clone` step, so it's really just this...
```sh
# install CLI
npm install -g reaction-cli

# clone Reaction, install NPM dependencies
reaction init

# move into the new app directory
cd reaction

# start Reaction
reaction
# or
reaction run
```
`reaction pull` is really just `git pull` under the hood, so that's not necessary in a fresh install.

**Comment by aaronjudd** [comment]
@mswaidan thanks, updated the installation docs and published.
