### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by akshayhalasangi** [reactioncommerce/reaction-docs#542]
Hello there,
I'm getting following error.. weird stuff

 npm install -g reaction-cli
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "reaction-cli"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! file /home/administrator/.npm/analytics-node/3.2.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/administrator/.npm/analytics-node/3.2.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/administrator/.npm/reaction-cli/0.28.0/package/npm-debug.log

Node - v6.11.4
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction Docs but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).
