### ISSUE TITLE
Better Shippo Documentation

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#550]
@willmoss1000 commented on [Mon Mar 05 2018](https://github.com/reactioncommerce/reaction-feature-requests/issues/33)

The current Shippo documentation is not sufficient for understanding the existing implementation.

**Comment by zenweasel** [comment]
Saying that the documentation should be "better" is not very actionable. If you could point to specific instances where it's lacking then this might be something we could work on.

**Comment by machikoyasuda** [comment]
Closing re: https://github.com/reactioncommerce/reaction/issues/4308
