### ISSUE TITLE
Starter Kit: Docs for MobX

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#575]
Docs can go in the `/docs` directory in the `reaction-next-starterkit` for now

**Comment by spencern** [comment]
@machikoyasuda @kieckhafer how do we feel about closing this issue or adding specific details around what docs remain to be created?

**Comment by machikoyasuda** [comment]
👍

**Comment by spencern** [comment]
Is that a 👍 close it or a 👍 add details?

**Comment by machikoyasuda** [comment]
👍 close and add new details in a new issue!
