### ISSUE TITLE
Screenshots of Hop Exchange for site showcase

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction-docs#580]
https://www.hop.exchange

**Comment by rymorgan** [comment]
@machikoyasuda @cindyfirestone 
![hop exchange](https://user-images.githubusercontent.com/20409254/40862713-34652cac-65a2-11e8-9630-596296f2e52c.jpg)

**Comment by rymorgan** [comment]
Looks like hop exchange use the swag shop tutorial b/c the pre-header is exactly the same 👍
