### ISSUE TITLE
Starter Kit: Document Keycloak integration with reaction-next-starterkit and GraphQL

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction-docs#587]
As part of the initial integration of [Keycloak](https://www.keycloak.org/) as an authentication/authorization solution, start documenting the login flow that the [reaction-next-starterkit](https://github.com/reactioncommerce/reaction-next-starterkit) will use.  

Initial work for that is currently under way at: https://github.com/reactioncommerce/reaction-next-starterkit/issues/103

Items to document:

- [ ] oauth login flow (redirects, etc)
- [ ] storage of token data on client
- [ ] access to token data on client/server
- [ ] inject/retrieve Keycloak user data in GraphQL context and Express request context

**Comment by spencern** [comment]
@jshimko I'd like to see each of these items broken out into their own issue if we haven't started work on them yet and linked to from here. You mentioned that some of these items have already been completed, if that's the case, let's check those boxes and link to the docs/PRs here.
