### ISSUE TITLE
Docs: Deployment: Add reaction-buildpack to official deployment resources

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#595]
https://github.com/Zanobo/reaction-buildpack

**Comment by zenweasel** [comment]
I think we may want to actually move this into an "official" plugin. I created a fork because we are relying on it for some of our projects

**Comment by machikoyasuda** [comment]
Awesome! Editing.

**Comment by machikoyasuda** [comment]
Closing this b/c you can't just deploy Reaction w/ just the meteor buildpack anymore...
