### ISSUE TITLE
Contributing Guide: Process: Publish a npm module for Reaction Commerce

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#605]
We have a lot of npm packages now: https://www.npmjs.com/~rc-publisher

We should document how to publish them, in a check list format.

Checklist:
- [ ] **Scaffolding**: Should the package be generated from https://github.com/reactioncommerce/generator-reaction-next or a basic scaffold copied from https://github.com/reactioncommerce/data-factory?
- [ ] **Linting**: https://github.com/reactioncommerce/reaction-eslint-config 
- [ ] **GitHub**: Add .github pull request, issue templates, .gitignore template, README.md template, Code of Conduct file, .npmignore
- [ ] **CircleCI**: config.yml
- [ ] **License**: What license to use?
- [ ] **Publish**: Publishing to rc-publisher and NPM
- [ ] **Versioning**: Semantic release versioning

Also, question: Should we make a scaffolding repo with all the basic config files?

**Comment by spencern** [comment]
@machikoyasuda thanks for putting this checklist together
