### ISSUE TITLE
Contributing Guide: Process: Snyk error handling

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#606]
**Outline**
 - [ ] Write a general snyk overview
    - [ ] What is snyk
    - [ ] Why we use snyk
 - [ ] Testing for vulnerabilities
    - [ ] Testing Locally
    - [ ] Circle CI
 - [ ] Resolving vulnerabilities
    - [ ] Updating a vulnerable dependency
    - [ ] Ignoring a vulnerable dependency
 
**Questions**
- When should snyk run?
    - [ ] snyk only runs against a security/release branch?
    - [ ] snyk only runs when the package.json has changed?
    - [ ] snyk runs on every PR?

- How long to ignore a vulnerable dependency?
   - [ ] Low severity
   - [ ] Medium serverity
   - [ ] High serverity
   - [ ] Critical serverity

**Comment by aldeed** [comment]
snyk does run on CI checks anymore so this doesn't seem necessary
