### ISSUE TITLE
Dev: Update prerender.io docs

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#609]
Update prerender.io docs for https://github.com/reactioncommerce/reaction/pull/4331 changes

**Comment by spencern** [comment]
@vwadher can your team help with this as you've recently successfully implemented prerender.io?

**Comment by zenweasel** [comment]
@ajporlante Can you take over this ticket and update the docs?

**Comment by ajporlante** [comment]
There is an existing PR for this: https://github.com/reactioncommerce/reaction-docs/pull/611
