### ISSUE TITLE
UI Style fixes

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction-docs#613]
- [ ] Fix spacing to match docs landing page below in the Zeplin designs. We're mostly going to match the former landing page on our design refresh with some new colors. 

https://zpl.io/VQYmlmA
- [x] Add/fix docs icon
- [ ] Make search bar a taller (like 8px border compared to 5px)
- [ ] Make underlined break instead of extending all the way to the edge

 ![screen_shot_2018-06-18_at_3_30_59_pm](https://user-images.githubusercontent.com/20409254/41565921-cc5bf2c0-730d-11e8-8cd2-05dedd4ee6b6.png)
- [ ] Make it so the article navigation doesn't cut off the headers

 ![uuuacu3l68](https://user-images.githubusercontent.com/20409254/41565927-d644dc5c-730d-11e8-9e46-60a136e1cd90.gif)
- [ ] Match footer styles to website

![screen shot 2018-06-18 at 3 38 38 pm](https://user-images.githubusercontent.com/20409254/41565938-e81332c6-730d-11e8-8fe5-2e226a3c31ab.png)

- [ ] Mobile search is a little funky, it has a shadow when you tap into the field, the icon isn't centered

![ezgif-5-927b7c6c0e](https://user-images.githubusercontent.com/20409254/41566782-ea490e04-7311-11e8-8e7b-aa9c0e0ed995.gif)

**Comment by machikoyasuda** [comment]
Issue moved to [reactioncommerce/reaction-docs-static #62](https://github.com/reactioncommerce/reaction-docs-static/issues/62) via [**ZenHub**](https://www.zenhub.com/)
