### ISSUE TITLE
Process of testing a PR for the base Reaction app with external/contrib packages

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#630]
@mikemurray commented on [Tue Jul 17 2018](https://github.com/reactioncommerce/reaction-docs-static/issues/106)

We should add a process doc for testing a PR for the base Reaction app in this new world where we've moved most of the packages that were included by default to external repos.

**Could be something like this:**

When testing a PR for the base Reaction app, only the base application and pre-installed packages should be used. This would ensure more consistent testing between team members and the community.

Issues with external contributed packages should be filed with the relevant issue tracker or maintaining party for that package. Those packages are responsible for their continued compatibility with the base Reaction app.

**Original discussion from @spencern**

> We should be testing with base packages. For something like address validation, ideally we’re testing the API with automated tests and then any additional testing would be the responsibility of the contrib package

for example: 
> If the issue is with Avalara [in a PR] (or even with the way that the Avalara plugin implements a new API) I would not consider that a blocker for [that PR], but instead an issue to be filed on the new Avalara repo

**Comment by spencern** [comment]
@mikemurray thanks for writing this up.
@jeffcorpuz I think your insight here would be valuable .

A few general goals:
- The base app can always be tested and run without any dependencies on a `contrib` package
- Contrib packages should run with the base app, but be tested independently.
- Contrib packages should be able to depend on a specific API in the core application that is documented (may need to do this still for some types of plugins) and versioned (right now this is the app version)
- A contrib package should note the versions of the core app that it's known to work with (e.g. 1.5.0 - 1.13.0)
- Moving included packages to contrib should result in a lighter core application and less total testing burden when testing the core application
