### ISSUE TITLE
Docs site not showing images.

### ISSUE THREAD

**Issue by WraithKenny** [reactioncommerce/reaction-docs#636]
Type: **minor**

**Describe the bug**
https://cdn.rawgit.com/reactioncommerce/reaction-docs/master/assets/svg/reaction-commerce-developer-guide.svg is 404.

**To Reproduce**
1. Go to 'https://docs.reactioncommerce.com/docs/next/intro
2. See error

**Expected behavior**
Image shouldn't be 404

**Comment by machikoyasuda** [comment]
@WraithKenny Thanks for bringing this to our attention. It should be all fixed now!
