### ISSUE TITLE
document git autocrlf config for windows dev setup

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction-docs#706]
We've had a few developers hit [this issue with graphql unterminated string constant](https://github.com/reactioncommerce/reaction/issues/4779) which is caused by git on windows. I'd like to see us document this setting in the install instructions to maybe avoid this issue. To set the configuration from the command line, use this command:

`git config --global core.autocrlf input`

**Comment by isaak-zmg** [comment]
@focusaurus  After I use this directive, the problem of re reaction still exists.

**Comment by focusaurus** [comment]
This setting effects the git clone operation. Did you delete your working
directory and clone the repository again?

**Comment by machikoyasuda** [comment]
Reaction no longer officially support Windows, so going to close this issue.
