### ISSUE TITLE
Broken link on "Reaction at a Glance" page

### ISSUE THREAD

**Issue by davidnagli** [reactioncommerce/reaction-docs#727]
Type: **breaking**

**Describe the bug**
The demo swag shop link on the [Reaction at a Glance](https://docs.reactioncommerce.com/docs/intro-glance) page is broken; it redirects me back to the Reaction landing page. 

This appears to be a DNS issue since the href of the link looks pretty legit, it doesn't actually go to the right page.

**To Reproduce**
1. Go to [Reaction at a Glance](https://docs.reactioncommerce.com/docs/intro-glance)
2. Scroll down to [Demo](https://docs.reactioncommerce.com/docs/intro-glance#demo)
3. Click on the "Demo Swag" shop link (href: [
https://swag.getreaction.io/](
https://swag.getreaction.io/) )
4. Get redirected to [https://www.reactioncommerce.com](https://www.reactioncommerce.com)

**Expected behavior**
Expected to see a demo swag store.

**Screenshots**
![screen shot 2019-01-27 at 12 01 59 pm](https://user-images.githubusercontent.com/6759650/51804166-6120fa00-222b-11e9-98be-fb941c8e30ef.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari
 - Version 12.0.1 (14606.2.104.1.1)

**Comment by machikoyasuda** [comment]
Hi @davidnagli - Sorry about this. The Demo Swag shop is no longer live. Going to remove the link. Thank you for the heads up.
