### ISSUE TITLE
Markdown linting config

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction-docs#74]
In response to the comment about Code Climate linting issues in #71...

I didn't even know markdown was getting linted.  We don't have a lint config in this repo and the linter library that CodeClimate uses is written in Ruby.  Other than the hassle of Ruby dependencies, the Atom plugin for that library doesn't update warnings on the fly for me.  I have to save the file to check for linting changes.

Can we consider switching to a Node based markdown linting lib like [remark-lint](https://github.com/wooorm/remark-lint) and start using a config in the repo?

http://remark.js.org/
https://github.com/wooorm/remark
https://github.com/wooorm/remark-lint
https://github.com/wooorm/remark-lint#configuring-remark-lint
https://github.com/wooorm/remark-lint#editor-integrations

I realize Code Climate doesn't support Remark, but I could [create a new engine](https://docs.codeclimate.com/docs/building-a-code-climate-engine) and submit it to them.  It's just a basic Docker image that processes the repo files.  It'd likely only require copying a similar engine and changing a few small details.  Either way, the Ruby deps with save-and-check workflow is suboptimal.  

You can install [remark-lint](https://github.com/wooorm/remark-lint) globally with npm and then  just add [linter-markdown](https://github.com/AtomLinter/linter-markdown) to Atom.

``` sh
npm i -g remark-lint
apm install linter-markdown
```

Then we'd just need to add a `.remarkrc` file to override the same defaults that our current linter ignores.

Thoughts?

**Comment by zenweasel** [comment]
If we could improve the quality of the linting that would be great. The current engine does not support any configuration and some of the default configuration is sort of bogus.

**Comment by aaronjudd** [comment]
Is this completed?

**Comment by aaronjudd** [comment]
Added BitHound and removed Code Climate on docs.
