### ISSUE TITLE
Screenshots for new additions to Site Showcase

### ISSUE THREAD

**Issue by cshivaratri** [reactioncommerce/reaction-docs#742]
Add the following sites to the site showcase.

https://www.icemachinesplus.com/

https://www.dispatchcoffee.ca/

https://classactdesigns.com

**Comment by cshivaratri** [comment]
@rymorgan can you help pull screenshots for the three sites listed.

**Comment by rymorgan** [comment]
@cshivaratri - here you go. 

![Dispatch coffee](https://user-images.githubusercontent.com/20409254/54571481-18bac880-49a0-11e9-8e44-df11d7d32198.png)
![Class act designs](https://user-images.githubusercontent.com/20409254/54571482-18bac880-49a0-11e9-992c-e25ffdc21e81.png)
![Ice machines](https://user-images.githubusercontent.com/20409254/54571483-18bac880-49a0-11e9-9ba2-aeb51159d8e8.png)
