### ISSUE TITLE
Clean up commit signing docs

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-docs#756]
Several repos now require signed commits from third-party contributors, but as far as I can tell, we only have instructions here: https://github.com/reactioncommerce/reaction-component-library/blob/master/docs/contributing.md#signing-your-commits

Which is in component library repo.

I've seen a few community PRs come in on other repos without signing, and it's hard to explain to them that they have to do it when we don't actually say that in most places.

We should do some combination of these:
- Update [main contributing docs](https://docs.reactioncommerce.com/docs/next/contributing-to-reaction)
- Put a similar "Signing your Commits" section in the `contributing.md` doc of every repo that requires it.
- Update PR description template to have a check box for it in repos where it is required

@roidrage @spencern @machikoyasuda

**Comment by machikoyasuda** [comment]
Are DCO's officially required on all open source Reaction repos now, even Docs? @spencern @roidrage

**Comment by machikoyasuda** [comment]
DCOs are now officially required on all Reaction open source repos, even Docs.

**Comment by machikoyasuda** [comment]
Assigning to @spencern cos he is working on updating the Contrib docs and PR Templates to add this new requirement.

**Comment by spencern** [comment]
Thanks @machikoyasuda and @aldeed 
Machiko and I have added notes to each rep's README and I'm working on updated Contributing docs and PR templates that will explain this further.

**Comment by spencern** [comment]
Just realized yesterday that I haven't added DCO instructions or submitted a PR to update the contributing docs yet. On my short list now.
