### ISSUE TITLE
Incorrect documentation in the "Register custom property as published" section

### ISSUE THREAD

**Issue by vadym-vorobel** [reactioncommerce/reaction-docs#773]
Type: **minor**

**Describe the bug**

Hi there!

Here we have documentation about extending the list of properties to be published.
https://docs.reactioncommerce.com/docs/how-to-extend-product#register-custom-property-as-published

It says that we need to register the keys `catalog.customPublishedProductFields` and `catalog.customPublishedProductVariantFields`.

But in fact, they should have names **catalog.publishedProductFields** and **catalog.publishedProductVariantFields**.

Here is a link to the appropriate code: https://github.com/localst/jfpbackend/blob/master/imports/plugins/core/core/server/Reaction/core.js#L131

Thanks!

**Comment by machikoyasuda** [comment]
Hi @vadym-vorobel - This link: https://github.com/localst/jfpbackend/blob/master/imports/plugins/core/core/server/Reaction/core.js#L131 goes to a private fork. Perhaps this fork is not updated with the latest changes from 2.0, release candidate 5.

As of release candidate 5, you can register `catalog.customPublishedProductFields` and `catalog.publishedProductVariantFields`, as seen here: https://github.com/reactioncommerce/reaction/blob/v2.0.0-rc.5/imports/plugins/core/core/server/Reaction/core.js#L14 and explained in the CHANGELOG here: https://github.com/reactioncommerce/reaction/blob/6c8e8066e7cf36057f93bbf4f08e836676c44896/CHANGELOG.md#additional-plugin-capabilities

**Comment by vadym-vorobel** [comment]
@machikoyasuda yeah, sorry, I missed this. Thanks for your answer
