### ISSUE TITLE
Remove all the hooks page as they are no longer supported in 

### ISSUE THREAD

**Issue by trojanh** [reactioncommerce/reaction-docs#779]
Type: **major**

Remove all the hooks page as they are no longer supported
https://docs.reactioncommerce.com/docs/method-hooks
https://docs.reactioncommerce.com/docs/collection-hooks
https://docs.reactioncommerce.com/docs/event-hooks

Will try to work on this to remove these pages but will do over the weekend.

**Comment by machikoyasuda** [comment]
Hi @trojanh - This is done in Next: https://docs.reactioncommerce.com/docs/next/intro

It'll be released when 2.0 is officially released.
