### ISSUE TITLE
[AUDIT] SOG Introduction into tagging concept

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-docs#791]
Audit this page: https://docs.reactioncommerce.com/docs/tagging

This means running through all instructions on the page, updating any out of date screenshots, correcting any incorrect documentation, and removing any out-of-date documentation.

**Comment by loan-laux** [comment]
Solved in #922.

**Comment by kieckhafer** [comment]
Thanks @loan-laux
