### ISSUE TITLE
[AUDIT] SOG Social Settings page

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-docs#795]
Audit this page: https://docs.reactioncommerce.com/docs/social-settings

This means running through all instructions on the page, updating any out of date screenshots, correcting any incorrect documentation, and removing any out-of-date documentation.

**Comment by loan-laux** [comment]
Do we even want to keep these fields (and thus this docs page) alive? As far as I'm aware, the social sharing feature got dropped from Reaction 2.0. The fields are somehow still there on the product form, but all they do is store a sharing message which could only be used by a third-party plugin at this stage.

**Comment by kieckhafer** [comment]
I think it's fine to drop them from the docs
