### ISSUE TITLE
[AUDIT] SOG Merchant Shop Setup page

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-docs#797]
Audit this page: https://docs.reactioncommerce.com/docs/merchant-shop-setup

This means running through all instructions on the page, updating any out of date screenshots, correcting any incorrect documentation, and removing any out-of-date documentation.

**Comment by loan-laux** [comment]
Solved as part of #931.

**Comment by kieckhafer** [comment]
thanks @loan-laux
