### ISSUE TITLE
Broken images in product administration section

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-docs#8]
Not sure if this is here or in `redoc` but all the images on this page https://reactioncommerce.com/docs/development/products are broken.

**Comment by aaronjudd** [comment]
That's because that's our old docs... `https://reactioncommerce.com/docs/development/products`  not, docs.reactioncommerce.com.    We should do something about that...

**Comment by zenweasel** [comment]
Fixed
