### ISSUE TITLE
Update content: Recommended tools

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#837]
Add https://github.com/reactioncommerce/reaction-devtools to https://docs.reactioncommerce.com/docs/next/recommended-tools and for ALL of the previous versions as well.

Link to the instructions on how to use it in Test setup.

**Comment by loan-laux** [comment]
`reaction-devtools` is no more, but maybe we could recommend [`@outgrowio/reaction-dummy-data`](http://github.com/outgrow/reaction-dummy-data) instead?
