### ISSUE TITLE
Docs: Audit - Reaction at a Glance

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-docs#844]
Audit: https://docs.reactioncommerce.com/docs/intro-glance @cshivaratri @reaction-justin 

Should this page still exist? Is all of this information covered on reactioncommerce.com? Or appropriate READMEs?

This page was created long ago because we had "frequently asked questions" that we didn't know where else to put the answers to.

**Comment by reaction-justin** [comment]
Could use an update at minimum. Let's strategize next week about maintaining this info in multiple locations or not.
