### ISSUE TITLE
Deployment instructions are outdated

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction-docs#883]
Type: **critical**

**Describe the bug**
The [`Deploying`](https://docs.reactioncommerce.com/docs/deploying) page still contains instructions for 1.x, referencing amongst other things `reaction deploy` and Meteor Galaxy. It should be deleted as a short-term solution, and replaced by more up-to-date instructions later on.

**To Reproduce**
1. Go the docs
2. Click on `Deploying` in the left-hand sidebar
3. Try to follow the instructions, which you don't know are outdated because you're new to RC
4. Fail miserably, be frustrated
5. Get a bad impression of the platform

**Expected behavior**
Up to date instructions should be provided for deploying Reaction Commerce 2.x.

**Comment by agustif** [comment]
+1, would love to help document it more if someone helps on which direction to investigate/try

**Comment by aldeed** [comment]
@loan-laux I think this was since updated.

**Comment by loan-laux** [comment]
Indeed it has, @aldeed. Thanks!
