### ISSUE TITLE
Does `featuredProductsByShop` GraphQL query exist anymore?

### ISSUE THREAD

**Issue by trojanh** [reactioncommerce/reaction-docs#891]
Type: **major**

**Describe the bug**
I couldn't find [`featuredProductsByShop` GraphQL query](https://github.com/reactioncommerce/reaction-docs/blob/master/public-docs/swag-shop-08-creating-featured-products-component.md) mentioned in docs anywhere on [reaction repo](https://github.com/reactioncommerce/reaction). It is removed in favor of `tag.featuredProductIds` ? 

If it doesn't exist, we will need to update the docs in below file
https://github.com/reactioncommerce/reaction-docs/blob/master/public-docs/swag-shop-08-creating-featured-products-component.md

**To Reproduce**
1. Go to https://docs.reactioncommerce.com/docs/swag-shop-8#docsNav
2. See `featuredProductsByShop` query 
3. Try to find it in Reaction and Reaction-admin repos.

**Expected behavior**
Either the GraphQL query  needs to exist or the docs need to be updated

**Comment by mikemurray** [comment]
@trojanh This function was to be used in conjunction with a custom plugin that has a tutorial in our docs: https://docs.reactioncommerce.com/docs/swag-shop-7#docsNav

To get featured products by tag, you can use the `catalogItems` query with `sortBy: featured`.

**Comment by spencern** [comment]
@trojanh A PR that makes the docs more clear in this case would be quite helpful

**Comment by trojanh** [comment]
@mikemurray thanks for the clarification. 

@spencern I'll create a PR for that soon.
