### ISSUE TITLE
Image need to be updated to reflect V3.0  changes.

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction-docs#903]
Type:**minor**

**Image has reference to old folder structure**
File Name `graphql-resolvers-file-structure.png` in 
https://github.com/reactioncommerce/reaction-docs/blob/trunk/public-docs/graphql-resolvers-file-structure.md
shown as: having  `no-meteor` reference.
![image](https://user-images.githubusercontent.com/14071646/74339017-3fa89700-4dc9-11ea-816c-a069cef2196a.png)

Please change this to:
![image](https://user-images.githubusercontent.com/14071646/74338443-2f43ec80-4dc8-11ea-9e75-53652ac50afd.png)

**Comment by spencern** [comment]
Good find. Thanks @hrath2015.
