### ISSUE TITLE
Environment variables documentation HTML table is unreadable

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction-docs#906]
Type: **minor**

**Describe the bug**

We have used an HTML table to organize our documentation around environment variables. This material has far too many long words and paragraphs to be readable in a table. The word wrapping becomes absurd.

**To Reproduce**

https://docs.reactioncommerce.com/docs/environment-variables

**Expected behavior**

Please just use headers, paragraphs, etc.

**Screenshots**
![screen-2020-02-19-15:53:51-env-var-docs-table](https://user-images.githubusercontent.com/482377/74884424-610d0400-5330-11ea-8cd0-60dfaeef52c4.png)

**Comment by aldeed** [comment]
I think using a table is fine, but I couldn't figure out how to override our styles to let the table be bigger and scroll horizontal. If anyone knows docusaurus styling, it shouldn't be difficult.

**Comment by nnnnat** [comment]
@reactioncommerce/design
