### ISSUE TITLE
Concepts Shops needs to be updated

### ISSUE THREAD

**Issue by HarisSpahija** [reactioncommerce/reaction-docs#923]
**Describe the documentation you'd like to read:**
https://docs.reactioncommerce.com/docs/concepts-shops

**Problem**
Currently the documentation states that Reaction Commerce is supporting that multi-shop systems are supported. ~~This is currently false~~ (EDIT): This is currently false for Reaction Admin. It still works on the API but needs to be obvious as it might give the wrong impression to developers reading the documentation. This should be either be removed or updated to state that it will be supported in the future.

**Comment by loan-laux** [comment]
It's actually true, but only on the API. I'll update with a disclaimer saying that `reaction-admin` and `example-storefront` aren't yet wired for multi-shop, but the API is. I'll also add a disclaimer saying that multi-vendor marketplaces won't be officially supported for now, with a link to `@outgrowio/reaction-marketplace` if that's not an issue with anybody.
