### ISSUE TITLE
Create Windows Tutorial using WSL and Linux

### ISSUE THREAD

**Issue by HarisSpahija** [reactioncommerce/reaction-docs#924]
**Describe the documentation you'd like to read:**
Some developers are using Windows or Linux. Currently we do not have an implementation or documentation in place for these users. In order to meet everyone's needs of working in their own environment Reaction should be compatible with Windows and Linux. 

- [ ] To ensure that developers can start working on Reaction with Windows and Linux we have to create a guide on how to change the install files in order for Reaction to work on Windows and Linux

- [ ] To ensure that developer have the right tools to work on Reaction we need to state what tools need to be installed beforehand. 

- [ ] To be transparent with the developers using Reaction we have to make sure that the limitations of the current platform and make is stated somewhere. This way people that are starting Reaction are not confronted with unknown bugs/limitations.

**Comment by brent-hoover** [comment]
I currently work on Linux as do several core Reaction developers and have not needed to make any changes to installation files to have them work.

**Comment by HarisSpahija** [comment]
What version of Linux are they running @zenweasel, perhaps that different dists handle reaction in their own way? We noticed from users that for example fedora was actually struggeling with the docker images.

**Comment by brent-hoover** [comment]
@HarisSpahija I am running PopOS (Ubuntu blend) and I believe @rosshadden is running Arch but I don't know for sure

**Comment by HarisSpahija** [comment]
Is there anyone that can confirm that fedora is working as expected out of the box? Would be appreciated so I can scrap Linux off the guide on how to run. 
Can someone add the tag "help-wanted"

**Comment by HarisSpahija** [comment]
Hi, quick update on this. I was able to set everything up with WSL2 out of the box functionality. I will write a guide about this in case people are stuck with this.
