### ISSUE TITLE
Merchant Shop Setup is outdated and should be removed

### ISSUE THREAD

**Issue by HarisSpahija** [reactioncommerce/reaction-docs#926]
**Describe the documentation you'd like to read:**
https://docs.reactioncommerce.com/docs/merchant-shop-setup

This part of the documentation seems to be out of sync with the current 3.x implementation and should be removed.

**Comment by loan-laux** [comment]
Since this versioned page is kept for backwards compatibility of the docs, I don't think we can remove it. However I'd recommend to put a huge deprecation disclaimer instead of the content.

**Comment by loan-laux** [comment]
Done. This is what you'll see now on this page, but earlier versions remain accessible.

<img width="1320" alt="Screen Shot 2020-04-08 at 20 41 30" src="https://user-images.githubusercontent.com/45489203/78821156-576f5680-79d9-11ea-84ef-5135046f2639.png">

Submitting this PR right away.
