### ISSUE TITLE
Issues Lauching on Windows

### ISSUE THREAD

**Issue by AceRex** [reactioncommerce/reaction-docs#939]
I am having to launch on widows, I have tried Yarn start and Npm run still not working I tried create-react app as well its still not working, can you help with a way out please

**Comment by focusaurus** [comment]
@AceRex are you talking about reaction-docs specifically or trying to run a full reaction platform via reaction-development-platform? Reaction does not provide support for running on windows at this time, so you'll need to try mac or linux or look to the community for support on windows.
