### ISSUE TITLE
Clarify getting started path

### ISSUE THREAD

**Issue by travis5491811** [reactioncommerce/reaction-docs#949]
Hello,

Can you please clarify the getting started path? Did I miss something? I'm currently evaluating reaction to see if I will introduce to our team. When going through the docs, [this page](https://docs.reactioncommerce.com/docs/installation-reaction-platform) appears incorrect. 

> 7. Congrats 🎉 Now you're running the entire suite of Reaction Development Platform services and ready to start developing.
> **Note: To login into the Operator UI use the credentials found in the [env.example](https://github.com/reactioncommerce/reaction/blob/v2.9.1/.env.example#L11-L12) file.**

When I try that login, its invalid. My .env.example file does not have the following two lines:

```
REACTION_AUTH=r3@cti0n
REACTION_EMAIL=admin@localhost
```

This is what my `reaction/.env.example` looks like:

```
MONGO_URL=mongodb://mongo.reaction.localhost:27017/reaction
ROOT_URL=http://localhost:3000
STRIPE_API_KEY=YOUR_PRIVATE_STRIPE_API_KEY
```

Plus my mongodb users collection was empty.  In order to access `http://localhost:4080/` I had to create a user through the front-end GUI

[This page](https://github.com/reactioncommerce/reaction) says to get started follow [this page](https://docs.reactioncommerce.com/docs/installation-reaction-platform) but after following that page and getting everything running correctly based on that page if I go back to continue on the previous page to "Start App in Docker Container (Recommended)", those steps are already done (mondodb container and reaction API already running).

I've managed to mussel my way into playing with reaction. But as a person new to the project, it's confusing trying to follow what I should be doing next when the initial goal is to get a demo up and running and see how well it works. I'm not sure if there is anything that can be done about it other than mentioning it. Maybe I'm the only one and/or I missed a step.

Currently evaluating: 

```
API Version: 3.8.0
MongoDB Version: 4.2.0
Installed Plugins:
simple-schema 1.0.0
job-queue 1.0.1
files 1.0.0
shops 1.0.1
settings 1.0.0
i18n 1.0.0
email 1.0.0
address-validation 1.3.0
plugin-translations 1.1.0
system-information 1.1.0
email-smtp 1.0.0
email-templates 1.0.0
accounts 1.3.0
authentication 1.1.0
authorization-simple 1.2.0
products 1.0.0
catalogs 1.0.2
tags 1.0.0
pricing-simple 1.0.0
inventory 1.0.1
inventory-simple 1.0.0
carts 1.2.0
orders 1.2.0
payments 1.0.0
payments-stripe 1.0.0
payments-example 1.1.0
discounts 1.0.0
discounts-codes 3.8.0
surcharges 1.1.0
shipments 1.0.0
shipments-flat-rate 1.0.0
taxes 1.0.0
taxes-flat-rate 1.0.1
navigation 1.1.0
sitemap-generator 1.2.0
notifications 1.0.0
address-validation-test 1.0.0
```

**Comment by willopez** [comment]
Hello this guide provides a high level overview: https://github.com/reactioncommerce/proxy-traefik

**Comment by focusaurus** [comment]
There's some doc WIP stuff Eric D started that's very relevant to this. I'm trying to track it down now then we can work to get it edited and published.

**Comment by focusaurus** [comment]
OK there's a bit more content somewhat related to this topic. There's a [new blog post on working with reaction 3.8.0](https://blog.reactioncommerce.com/working-with-reaction-3-8/) as well as a [docs section](https://docs.reactioncommerce.com/docs/next/core-plugins-developing) extracted from that blog post.

**Comment by balibebas** [comment]
> Hello this guide provides a high level overview: https://github.com/reactioncommerce/proxy-traefik

@willopez This is fantastic. I was sweating getting a demo online to get stakeholder buy-in on this platform and this is exactly what I was looking for. I was literally trying trying to follow the _Deployment_ docs just to get a test site up. You're a life saver.

@travis5491811 If you're running locally for demo purposes pull down the `reaction-development platform` and run `make` in the root directory. Then register a user at `localhost:4080` (Reaction Admin) once the development platform comes up and you should be good to go. The docs are a bit outdated as the platform is moving quickly.

**Comment by balibebas** [comment]
> Hello this guide provides a high level overview: https://github.com/reactioncommerce/proxy-traefik

@willopez This is fantastic. I was sweating getting a demo online to get stakeholder buy-in on this platform and this is exactly what I was looking for. I was literally trying to follow the _Deployment_ docs just to get a test site up ><. You're a life saver.

@travis5491811 If you're running locally for demo purposes pull down the `reaction-development platform` and run `make` in the root directory. Then register a user at `localhost:4080` (Reaction Admin) once the development platform comes up and you should be good to go. The docs are a bit outdated as the platform is moving quickly.

**Comment by ghost** [comment]
> Hello this guide provides a high level overview: https://github.com/reactioncommerce/proxy-traefik

@willopez This is fantastic. I was sweating getting a demo online to get stakeholder buy-in on this platform and this is exactly what I was looking for. I was literally trying to follow the _Deployment_ docs just to get a test site up ><. You're a life saver.

@travis5491811 If you're running locally for demo purposes pull down the `reaction-development-platform` and run `make` in the root directory. Then register a user at `localhost:4080` (Reaction Admin) once the development platform comes up and you should be good to go. The docs are a bit outdated as the platform is moving quickly.

**Comment by willopez** [comment]
@balibebas glad it helped out.
